# Generated by Django 4.2 on 2024-09-28 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://img.freepik.com/premium-vector/restaurant-logo-design_1128391-17280.jpg', max_length=500),
        ),
    ]
